{
 "title": "HttpRunner for Distributed Load Testing",
 "description": "HttpRunner for Distributed Load Testing",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(users{mode=\"worker\"})"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(users{mode=\"worker\"})"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_rps{mode=\"worker\"})"
    }
   ]
  },
  {
   "title": "Total Fail Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(total_num_failures{mode=\"worker\",method!~\"transation|testcase\"}) / sum(total_num_requests{mode=\"worker\", method!~\"transation|testcase\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total Fails Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(total_fail_per_sec{mode=\"worker\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_num_requests{mode=\"worker\",method!~\"transaction|testcase\"})"
    }
   ]
  },
  {
   "title": "Total Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_num_failures{mode=\"worker\",method!~\"transaction|testcsae\"})"
    }
   ]
  },
  {
   "title": "Total Response Times (PCT95/PCT50)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(response_time{mode=\"worker\", quantile=\"0.95\", method!~\"transaction|testcase\"}) by (name,method)",
     "legendFormat": "{{ method}} - {{name}} PCT95"
    },
    {
     "expr": "avg(response_time{mode=\"worker\", quantile=\"0.5\", method!~\"transaction|testcase\"}) by (name,method)",
     "legendFormat": "{{ method}} - {{name}} PCT50"
    }
   ]
  },
  {
   "title": "Total Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "total_max_response_time{name!~\"Total\",mode=\"worker\",method!~\"transaction|testcase\"}",
     "legendFormat": "{{ method}} - {{name}} MAX"
    },
    {
     "expr": "total_min_response_time{name!~\"Total\",mode=\"worker\",method!~\"transaction|testcase\"}",
     "legendFormat": "{{ method}} - {{name}} MIN"
    },
    {
     "expr": "response_time_sum{mode=\"worker\",method!=\"transaction\"} / response_time_count{mode=\"standalone\",method!~\"transaction|testcase\"}",
     "legendFormat": "{{ method}} - {{name}} AVG"
    },
    {
     "expr": "response_time{quantile=\"0.5\", mode=\"worker\",method!~\"transaction|testcase\"}",
     "legendFormat": "{{ method}} - {{name}} MEDIAN"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(errors{mode=\"worker\"}) by (method, name, error)"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "min(min_response_time{mode=\"worker\"}) by (method, name)"
    },
    {
     "expr": "max(max_response_time{mode=\"worker\"}) by (method, name)"
    },
    {
     "expr": "avg(average_response_time{mode=\"worker\"}) by (method, name)"
    },
    {
     "expr": "avg(median_response_time{mode=\"worker\"}) by (method, name)"
    },
    {
     "expr": "sum(current_rps{mode=\"worker\"}) by (method, name)"
    },
    {
     "expr": "sum(num_failures{mode=\"worker\"}) by (method, name)"
    },
    {
     "expr": "sum(num_requests{mode=\"worker\"}) by (method, name)"
    },
    {
     "expr": "sum(num_failures{mode=\"worker\"}) by (method, name) / sum(num_requests{mode=\"worker\"}) by (method, name)"
    }
   ]
  },
  {
   "title": "Response Times (3s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(max_response_time{mode=\"worker\", method!~\"transaction|testcase\"})",
     "legendFormat": "{{ method}} - {{name}} MAX"
    },
    {
     "expr": "min(min_response_time{mode=\"worker\", method!~\"transaction|testcase\"})",
     "legendFormat": "{{ method}} - {{name}} MIN"
    },
    {
     "expr": "avg(average_response_time{mode=\"worker\", method!~\"transaction|testcase\"})",
     "legendFormat": "{{ method}} - {{name}} AVG"
    },
    {
     "expr": "avg(median_response_time{mode=\"worker\", method!~\"transaction|testcase\"})",
     "legendFormat": "{{ method}} - {{name}} MEDIAN"
    }
   ]
  },
  {
   "title": "Requests Per Endpoint / s (3s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(current_rps{mode=\"worker\", method!~\"transaction|testcase\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Fails Per Endpoint / s (3s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(num_failures{mode=\"worker\",method!~\"transaction|testcase\"}) / sum(num_requests{mode=\"worker\",method!~\"transaction|testcase\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Transations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(total_num_requests{mode=\"worker\", method=\"transaction\", name!=\"Action\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(total_num_requests{mode=\"worker\", method=\"transaction\", name!=\"Action\"}) by (name)",
     "legendFormat": "{{method}}-{{name}}"
    }
   ]
  },
  {
   "title": "Transations Passed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(total_num_requests{mode=\"worker\", method=\"transaction\", name!=\"Action\"} - total_num_failures{mode=\"worker\", method=\"transaction\", name!=\"Action\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(total_num_requests{mode=\"worker\", method=\"transaction\", name!=\"Action\"}) by (name, method) - sum(total_num_failures{mode=\"worker\", method=\"transaction\", name!=\"Action\"}) by (name, method)",
     "legendFormat": "{{ method}} - {{name}}"
    }
   ]
  },
  {
   "title": "Transations Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(total_num_requests{mode=\"worker\", method=\"transaction\", name!=\"Action\"} - total_num_failures{mode=\"worker\", method=\"transaction\", name!=\"Action\"}) / sum(total_num_requests{mode=\"worker\", method=\"transaction\", name!=\"Action\"})",
     "legendFormat": "total"
    },
    {
     "expr": "(sum(total_num_requests{mode=\"worker\", method=\"transaction\", name!=\"Action\"}) by (method, name) - sum(total_num_failures{mode=\"worker\", method=\"transaction\", name!=\"Action\"}) by (method, name)) / sum(total_num_requests{mode=\"worker\", method=\"transaction\", name!=\"Action\"}) by (method, name)",
     "legendFormat": "{{method}}-{{name}}"
    }
   ]
  }
 ]
}