{
 "title": "HttpRunner for Standalone Load Testing",
 "description": "HttpRunner Load Testing",
 "tags": [ "HttpRunner" ],
 "time": { "from": "now-30s", "to": "now" },
 "panels": [
  {
   "title": "HttpRunner Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state{mode=\"standalone\"}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "users{mode=\"standalone\"}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_num_requests{mode=\"standalone\",method!=\"transaction\"})"
    }
   ]
  },
  {
   "title": "Total Fail Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(total_num_failures{mode=\"standalone\",method!=\"transaction\"}) / sum(total_num_requests{mode=\"standalone\",method!=\"transaction\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total Fails Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_fail_per_sec{mode=\"standalone\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_rps{mode=\"standalone\"}"
    }
   ]
  },
  {
   "title": "Total Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_num_failures{mode=\"standalone\",method!=\"transaction\",name!=\"Action\"})"
    }
   ]
  },
  {
   "title": "Total Response Times (PCT95/PCT50)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(response_time{quantile=\"0.95\",method!~\"transaction\",mode=\"standalone\"}) by (name,method)",
     "legendFormat": "{{ method}} - {{name}} PCT95"
    },
    {
     "expr": "avg(response_time{quantile=\"0.5\",method!~\"transaction\",mode=\"standalone\"}) by (name,method)",
     "legendFormat": "{{ method}} - {{name}} PCT50"
    }
   ]
  },
  {
   "title": "Total Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "total_max_response_time{name!~\"Action|Total\",mode=\"standalone\",method!=\"transaction\"}",
     "legendFormat": "{{ method}} - {{name}} MAX"
    },
    {
     "expr": "total_min_response_time{name!~\"Action|Total\",mode=\"standalone\",method!=\"transaction\"}",
     "legendFormat": "{{ method}} - {{name}} MIN"
    },
    {
     "expr": "response_time_sum{name!=\"Action\",mode=\"standalone\",method!=\"transaction\"} / response_time_count{name!=\"Action\", mode=\"standalone\",method!=\"transaction\"}",
     "legendFormat": "{{ method}} - {{name}} AVG"
    },
    {
     "expr": "response_time{quantile=\"0.5\", name!=\"Action\",mode=\"standalone\",method!=\"transaction\"}",
     "legendFormat": "{{ method}} - {{name}} MEDIAN"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(errors{mode=\"standalone\"}) by (method, name, error)"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(min_response_time{name!=\"Action\",mode=\"standalone\"}) by (method, name)"
    },
    {
     "expr": "sum(max_response_time{name!=\"Action\",mode=\"standalone\"}) by (method, name)"
    },
    {
     "expr": "sum(average_response_time{name!=\"Action\",mode=\"standalone\"}) by (method, name)"
    },
    {
     "expr": "sum(median_response_time{name!=\"Action\",mode=\"standalone\"}) by (method, name)"
    },
    {
     "expr": "sum(current_rps{name!=\"Action\",mode=\"standalone\"}) by (method, name)"
    },
    {
     "expr": "sum(num_failures{name!=\"Action\",mode=\"standalone\"}) by (method, name)"
    },
    {
     "expr": "sum(num_requests{name!=\"Action\",mode=\"standalone\"}) by (method, name)"
    },
    {
     "expr": "num_failures{name!=\"Action\",mode=\"standalone\"} / num_requests{name!=\"Action\",mode=\"standalone\"}"
    }
   ]
  },
  {
   "title": "Response Times (3s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(max_response_time{mode=\"standalone\",method!=\"transaction\"}) by (method, name)",
     "legendFormat": "{{ method}} - {{name}} MAX"
    },
    {
     "expr": "sum(min_response_time{mode=\"standalone\",method!=\"transaction\"}) by (method, name)",
     "legendFormat": "{{ method}} - {{name}} MIN"
    },
    {
     "expr": "sum(average_response_time{mode=\"standalone\",method!=\"transaction\"}) by (method, name)",
     "legendFormat": "{{ method}} - {{name}} AVG"
    },
    {
     "expr": "sum(median_response_time{mode=\"standalone\",method!=\"transaction\"}) by (method, name)",
     "legendFormat": "{{ method}} - {{name}} MEDIAN"
    }
   ]
  },
  {
   "title": "Requests Per Endpoint / s (3s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "current_rps{mode=\"standalone\",method!=\"transaction\",name!=\"Action\"}",
     "legendFormat": "{{ method}} - {{name}}"
    },
    {
     "expr": "current_fail_per_sec{mode=\"standalone\",method!=\"transaction\",name!=\"Action\"}",
     "legendFormat": "{{ method}} - {{name}} fail_ratio [%]"
    }
   ]
  },
  {
   "title": "Fails Per Endpoint / s (3s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_fail_per_sec{mode=\"standalone\"}"
    }
   ]
  },
  {
   "title": "Transations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(total_num_requests{method=\"transaction\", name!=\"Action\"})",
     "legendFormat": "total"
    },
    {
     "expr": "total_num_requests{method=\"transaction\", name!=\"Action\"}",
     "legendFormat": "{{method}}-{{name}}"
    }
   ]
  },
  {
   "title": "Transations Passed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(total_num_requests{method=\"transaction\", name!=\"Action\"} - total_num_failures{method=\"transaction\", name!=\"Action\"})",
     "legendFormat": "total"
    },
    {
     "expr": "total_num_requests{method=\"transaction\", name!=\"Action\"} - total_num_failures{method=\"transaction\", name!=\"Action\"}",
     "legendFormat": "{{ method}} - {{name}}"
    }
   ]
  },
  {
   "title": "Transations Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(total_num_requests{method=\"transaction\", name!=\"Action\"} - total_num_failures{method=\"transaction\", name!=\"Action\"}) / sum(total_num_requests{method=\"transaction\", name!=\"Action\"})",
     "legendFormat": "total"
    },
    {
     "expr": "(total_num_requests{method=\"transaction\", name!=\"Action\"} - total_num_failures{method=\"transaction\", name!=\"Action\"}) / total_num_requests{method=\"transaction\", name!=\"Action\"}",
     "legendFormat": "{{method}}-{{name}}"
    }
   ]
  }
 ]
}